#!/usr/bin/env python
a = int(input("Entrez le Ie nombre !\n"))
b = int(input("Entrez le IIe nombre !\n"))
c = int(input("Entrez le IIIe nombre !\n"))
d = int(input("Entrez le IVe nombre !\n"))

if a == b == c == d:
    print("Les nombres sont égaux.")
elif (a == b == c and d != c) or (a == b == d and c != a) or (b == c == d and a != b) or (a == c == d and b != a):
    print("Trois nomres sont égaux et un est distinct.")
elif (a == b and c != d and c != a and d !=a) ^ (a == c and d != b and b != a and d != a) ^ (a == d and c != b and c != a and b != a) ^ (b == c and a != d and d != c and c != a) ^ (b == d and a != c and a != b and c != b) ^ (d == c and a != b and b != c and c != a):
    print("Deux nombres sont égaux, les deux autres distincts des deux premiers et entre eux.")
elif a!= b and a != b and a != c and b != c and b != d and c != d:
    print("Tous les nombres sont distincts")
else:
    if (a == b and c == d and a != c) ^ (a == c and b == d and a != b) ^ (a == d and c == b and a != c):
        print("Les nombres sont égaux 2 à 2, sans être tous les quatres égaux.")