#!/usr/bin/env python
h = int(input("Entrez l'heure !\n"))

if h >= 25:
    print("420?")
else:
    m = int(input("Entrez la minute !\n"))
    if h >= 0 and h < 24:
        if m >= 0 and m < 60:
            print(f"Dans une minute, il sera {h} heure(s) {m+1}.")
        if m == 60:
            print(f"Dans une minute, il sera {h+1} heures.")
if h == 24:
    if m >= 0 and m < 60:
        print(f"Dans une minute, il sera {h} heure(s) {m+1}.")
    if m == 60:
        print("Dans une minute, il sera minuit/midi.") 
