#!/usr/bin/env python
jour = int(input("Entrez le code du jour [0:Lundi...] : "))
heure = int(input("Entrez le code de l'heure [0,...,23] : "))
while jour < 0 or jour >= 7:
    print("Format de jour invalide")
    jour = int(input("Entrez le code du jour [0:Lundi...] : "))
while heure < 0 or heure >= 24:
    print("Format d'heure invalide")
    heure = int(input("Entrez le code de l'heure [0,...,23] : "))
a = heure >= 7 and heure < 13 and jour != 1
b = heure >= 16 and heure < 20 and jour > 1
if a or b:
    print("La boulangerie est ouverte.")
else:
    print("La boulangerie est fermée.")
