#!/usr/bin/env python
j = int(input("Entrez le code du jour !\n"))


if j<=6 and j >=2:
    print("La boulangerie est ouverte !")
elif j == 0:
    h = int(input("Entrez le code de l'heure !\n"))
    if ((h >= 7 and h < 13) or (h >= 16 and h < 20)):
        print("La boulangerie est ouverte !")
    else:
        print("La boulangerie est fermée.")
elif j == 1:
    print("La boulangerie est fermée.")
else:
    print("42")
