#!/usr/bin/env python
l = input("Entrez la liste > ")

def triParPropagation(l):
     renverse = True
     while renverse:
             renverse = False
             for i in range(len(l)-1):
                     if l[i] > l[i+1]:
                             l[i], l[i+1] = l[i+1], l[i]
                             renverse = True

print(triParPropagation(l))
